import {  Raleway } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { BasketProvider } from "./context/BasketContext";


const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">

      <body className={`${raleway.variable}`}>
        
        <BasketProvider>

            <Header/>

            {children}

            <Footer/>

        </BasketProvider>

      </body>


    </html>
  );
}
